insert into "investmentApp_asset"(id,description,code) values(1,'3 R Petroleum','RRRP3');
insert into "investmentApp_asset"(id,description,code) values(2,'3tentos','TTEN3');
insert into "investmentApp_asset"(id,description,code) values(3,'Aco Altona','EALT3');
insert into "investmentApp_asset"(id,description,code) values(4,'Aco Altona','EALT4');
insert into "investmentApp_asset"(id,description,code) values(5,'Advanced Dh','ADHM3');
insert into "investmentApp_asset"(id,description,code) values(6,'Aeris','AERI3');
insert into "investmentApp_asset"(id,description,code) values(7,'Aes Brasil','AESB3');
insert into "investmentApp_asset"(id,description,code) values(8,'Aes Tiete E','TIET11');
insert into "investmentApp_asset"(id,description,code) values(9,'Aes Tiete E','TIET3');
insert into "investmentApp_asset"(id,description,code) values(10,'Aes Tiete E','TIET4');
insert into "investmentApp_asset"(id,description,code) values(11,'Afluente T','AFLT3');
insert into "investmentApp_asset"(id,description,code) values(12,'Agribrasil','GRAO3');
insert into "investmentApp_asset"(id,description,code) values(13,'Agrogalaxy','AGXY3');
insert into "investmentApp_asset"(id,description,code) values(14,'Alfa Consorc','BRGE11');
insert into "investmentApp_asset"(id,description,code) values(15,'Alfa Consorc','BRGE12');
insert into "investmentApp_asset"(id,description,code) values(16,'Alfa Consorc','BRGE3');
insert into "investmentApp_asset"(id,description,code) values(17,'Alfa Consorc','BRGE5');
insert into "investmentApp_asset"(id,description,code) values(18,'Alfa Consorc','BRGE6');
insert into "investmentApp_asset"(id,description,code) values(19,'Alfa Consorc','BRGE7');
insert into "investmentApp_asset"(id,description,code) values(20,'Alfa Consorc','BRGE8');
insert into "investmentApp_asset"(id,description,code) values(21,'Alfa Financ','CRIV3');
insert into "investmentApp_asset"(id,description,code) values(22,'Alfa Financ','CRIV4');
insert into "investmentApp_asset"(id,description,code) values(23,'Alfa Holding','RPAD3');
insert into "investmentApp_asset"(id,description,code) values(24,'Alfa Holding','RPAD5');
insert into "investmentApp_asset"(id,description,code) values(25,'Alfa Holding','RPAD6');
insert into "investmentApp_asset"(id,description,code) values(26,'Alfa Invest','BRIV3');
insert into "investmentApp_asset"(id,description,code) values(27,'Alfa Invest','BRIV4');
insert into "investmentApp_asset"(id,description,code) values(28,'Alianscsonae','ALSO3');
insert into "investmentApp_asset"(id,description,code) values(29,'Alianza Trust Renda Imobiliaria Fundo Investimento Imobiliario','ALZR11');
insert into "investmentApp_asset"(id,description,code) values(30,'Alliar','AALR3');
insert into "investmentApp_asset"(id,description,code) values(31,'Allied','ALLD3');
insert into "investmentApp_asset"(id,description,code) values(32,'Alpargatas','ALPA3');
insert into "investmentApp_asset"(id,description,code) values(33,'Alpargatas','ALPA4');
insert into "investmentApp_asset"(id,description,code) values(34,'Alper S.A.','APER3');
insert into "investmentApp_asset"(id,description,code) values(35,'Alphabet DRN A','GOGL34');
insert into "investmentApp_asset"(id,description,code) values(36,'Alphaville','AVLL3');
insert into "investmentApp_asset"(id,description,code) values(37,'Alupar','ALUP11');
insert into "investmentApp_asset"(id,description,code) values(38,'Alupar','ALUP3');
insert into "investmentApp_asset"(id,description,code) values(39,'Alupar','ALUP4');
insert into "investmentApp_asset"(id,description,code) values(40,'Amazonia','BAZA3');
insert into "investmentApp_asset"(id,description,code) values(41,'Ambev S.A.','ABEV3');
insert into "investmentApp_asset"(id,description,code) values(42,'Ambipar','AMBP3');
insert into "investmentApp_asset"(id,description,code) values(43,'Ampla Energ','CBEE3');
insert into "investmentApp_asset"(id,description,code) values(44,'Anima','ANIM3');
insert into "investmentApp_asset"(id,description,code) values(45,'Arezzo Indústria e Comércio S.A.','ARZZ3');
insert into "investmentApp_asset"(id,description,code) values(46,'Armac','ARML3');
insert into "investmentApp_asset"(id,description,code) values(47,'Assai','ASAI3');
insert into "investmentApp_asset"(id,description,code) values(48,'AtmaSA','ATMP3');
insert into "investmentApp_asset"(id,description,code) values(49,'Atompar','ATOM3');
insert into "investmentApp_asset"(id,description,code) values(50,'Aura 360','AURA33');
insert into "investmentApp_asset"(id,description,code) values(51,'Azevedo','AZEV3');
insert into "investmentApp_asset"(id,description,code) values(52,'Azevedo','AZEV4');
insert into "investmentApp_asset"(id,description,code) values(53,'Azul S.A.','AZUL4');
insert into "investmentApp_asset"(id,description,code) values(54,'B2W - Companhia Digital','BTOW3');
insert into "investmentApp_asset"(id,description,code) values(55,'B3 S.A. - Brasil, Bolsa, Balcão','B3SA3');
insert into "investmentApp_asset"(id,description,code) values(56,'Bahema','BAHI3');
insert into "investmentApp_asset"(id,description,code) values(57,'Banco Bmg','BMGB4');
insert into "investmentApp_asset"(id,description,code) values(58,'Banco Bradesco S.A.','BBDC3');
insert into "investmentApp_asset"(id,description,code) values(59,'Banco Bradesco S.A.','BBDC4');
insert into "investmentApp_asset"(id,description,code) values(60,'Banco do Brasil S.A.','BBAS3');
insert into "investmentApp_asset"(id,description,code) values(61,'Banco do Estado do Rio Grande do Sul S.A.','BRSR6');
insert into "investmentApp_asset"(id,description,code) values(62,'Banco Inter','BIDI11');
insert into "investmentApp_asset"(id,description,code) values(63,'Banco Inter S.A.','BIDI4');
insert into "investmentApp_asset"(id,description,code) values(64,'Banco Inter S.A.','BIDI3');
insert into "investmentApp_asset"(id,description,code) values(65,'Banco Modal','MODL4');
insert into "investmentApp_asset"(id,description,code) values(66,'Banco Modal','MODL11');
insert into "investmentApp_asset"(id,description,code) values(67,'Banco Modal','MODL3');
insert into "investmentApp_asset"(id,description,code) values(68,'Banco Pan','BPAN4');
insert into "investmentApp_asset"(id,description,code) values(69,'Banco Santander (Brasil) S.A.','SANB3');
insert into "investmentApp_asset"(id,description,code) values(70,'Banco Santander (Brasil) S.A.','SANB11');
insert into "investmentApp_asset"(id,description,code) values(71,'Banese','BGIP3');
insert into "investmentApp_asset"(id,description,code) values(72,'Banese','BGIP4');
insert into "investmentApp_asset"(id,description,code) values(73,'Banestes','BEES3');
insert into "investmentApp_asset"(id,description,code) values(74,'Banestes','BEES4');
insert into "investmentApp_asset"(id,description,code) values(75,'Banpara','BPAR3');
insert into "investmentApp_asset"(id,description,code) values(76,'Banrisul','BRSR3');
insert into "investmentApp_asset"(id,description,code) values(77,'Banrisul','BRSR5');
insert into "investmentApp_asset"(id,description,code) values(78,'Bardella','BDLL3');
insert into "investmentApp_asset"(id,description,code) values(79,'Bardella','BDLL4');
insert into "investmentApp_asset"(id,description,code) values(80,'Battistella','BTTL3');
insert into "investmentApp_asset"(id,description,code) values(81,'Baumer','BALM3');
insert into "investmentApp_asset"(id,description,code) values(82,'Baumer','BALM4');
insert into "investmentApp_asset"(id,description,code) values(83,'BB Progressivo II Fundo de Investimento Imobiliario - FII','BBPO11');
insert into "investmentApp_asset"(id,description,code) values(84,'BB Seguridade Participações S.A.','BBSE3');
insert into "investmentApp_asset"(id,description,code) values(85,'Bemobi Tech','BMOB3');
insert into "investmentApp_asset"(id,description,code) values(86,'Bic Monark','BMKS3');
insert into "investmentApp_asset"(id,description,code) values(87,'Biomm','BIOM3');
insert into "investmentApp_asset"(id,description,code) values(88,'Biosev','BSEV3');
insert into "investmentApp_asset"(id,description,code) values(89,'Bk Brasil','BKBR3');
insert into "investmentApp_asset"(id,description,code) values(90,'Blau','BLAU3');
insert into "investmentApp_asset"(id,description,code) values(91,'Boa Safra','SOJA3');
insert into "investmentApp_asset"(id,description,code) values(92,'Boa Vista','BOAS3');
insert into "investmentApp_asset"(id,description,code) values(93,'Bombril','BOBR3');
insert into "investmentApp_asset"(id,description,code) values(94,'Bombril','BOBR4');
insert into "investmentApp_asset"(id,description,code) values(95,'Br Brokers','BBRK3');
insert into "investmentApp_asset"(id,description,code) values(96,'BR Malls Participações S.A.','BRML3');
insert into "investmentApp_asset"(id,description,code) values(97,'BR Partners','BRBI11');
insert into "investmentApp_asset"(id,description,code) values(98,'Br Propert','BRPR3');
insert into "investmentApp_asset"(id,description,code) values(99,'Bradespar S.A.','BRAP4');
insert into "investmentApp_asset"(id,description,code) values(100,'Bradespar S.A.','BRAP3');
insert into "investmentApp_asset"(id,description,code) values(101,'Brasilagro','AGRO3');
insert into "investmentApp_asset"(id,description,code) values(102,'Braskem','BRKM6');
insert into "investmentApp_asset"(id,description,code) values(103,'Braskem S.A.','BRKM5');
insert into "investmentApp_asset"(id,description,code) values(104,'Braskem S.A.','BRKM3');
insert into "investmentApp_asset"(id,description,code) values(105,'Brb Banco','BSLI3');
insert into "investmentApp_asset"(id,description,code) values(106,'Brb Banco','BSLI4');
insert into "investmentApp_asset"(id,description,code) values(107,'BRF S.A.','BRFS3');
insert into "investmentApp_asset"(id,description,code) values(108,'BriSAnet','BRIT3');
insert into "investmentApp_asset"(id,description,code) values(109,'BTG Pactual Logística','BTLG11');
insert into "investmentApp_asset"(id,description,code) values(110,'Btgp Banco','BPAC11');
insert into "investmentApp_asset"(id,description,code) values(111,'Btgp Banco','BPAC3');
insert into "investmentApp_asset"(id,description,code) values(112,'Btgp Banco','BPAC5');
insert into "investmentApp_asset"(id,description,code) values(113,'Caixa Seguri','CXSE3');
insert into "investmentApp_asset"(id,description,code) values(114,'Cambuci','CAMB3');
insert into "investmentApp_asset"(id,description,code) values(115,'Camil Alimentos S.A.','CAML3');
insert into "investmentApp_asset"(id,description,code) values(116,'Carrefour Br','CRFB3');
insert into "investmentApp_asset"(id,description,code) values(117,'CaSAn','CASN');
insert into "investmentApp_asset"(id,description,code) values(118,'CaSAn','CASN3');
insert into "investmentApp_asset"(id,description,code) values(119,'CaSAn','CASN4');
insert into "investmentApp_asset"(id,description,code) values(120,'CBA','CBAV3');
insert into "investmentApp_asset"(id,description,code) values(121,'CCR S.A.','CCRO3');
insert into "investmentApp_asset"(id,description,code) values(122,'Cea Modas','CEAB3');
insert into "investmentApp_asset"(id,description,code) values(123,'Ceb','CEBR3');
insert into "investmentApp_asset"(id,description,code) values(124,'Ceb','CEBR5');
insert into "investmentApp_asset"(id,description,code) values(125,'Ceb','CEBR6');
insert into "investmentApp_asset"(id,description,code) values(126,'Cedro','CEDO3');
insert into "investmentApp_asset"(id,description,code) values(127,'Cedro','CEDO4');
insert into "investmentApp_asset"(id,description,code) values(128,'Ceee D','CEED3');
insert into "investmentApp_asset"(id,description,code) values(129,'Ceee D','CEED4');
insert into "investmentApp_asset"(id,description,code) values(130,'Ceee Gt','EEEL3');
insert into "investmentApp_asset"(id,description,code) values(131,'Ceee Gt','EEEL4');
insert into "investmentApp_asset"(id,description,code) values(132,'Ceg','CEGR3');
insert into "investmentApp_asset"(id,description,code) values(133,'Celesc','CLSC3');
insert into "investmentApp_asset"(id,description,code) values(134,'Celesc','CLSC4');
insert into "investmentApp_asset"(id,description,code) values(135,'Celgpar','GPAR3');
insert into "investmentApp_asset"(id,description,code) values(136,'Celpe','CEPE3');
insert into "investmentApp_asset"(id,description,code) values(137,'Celpe','CEPE5');
insert into "investmentApp_asset"(id,description,code) values(138,'Celpe','CEPE6');
insert into "investmentApp_asset"(id,description,code) values(139,'Cemepe','MAPT3');
insert into "investmentApp_asset"(id,description,code) values(140,'Cemepe','MAPT4');
insert into "investmentApp_asset"(id,description,code) values(141,'Centrais Elétricas Brasileiras S.A. - Eletrobras','ELET3');
insert into "investmentApp_asset"(id,description,code) values(142,'Centrais Elétricas Brasileiras S.A. - Eletrobras','ELET6');
insert into "investmentApp_asset"(id,description,code) values(143,'Cesp','CESP3');
insert into "investmentApp_asset"(id,description,code) values(144,'Cesp','CESP5');
insert into "investmentApp_asset"(id,description,code) values(145,'Cesp','CESP6');
insert into "investmentApp_asset"(id,description,code) values(146,'Cia. Hering','HGTX3');
insert into "investmentApp_asset"(id,description,code) values(147,'Cielo S.A.','CIEL3');
insert into "investmentApp_asset"(id,description,code) values(148,'ClearSAle','CLSA3');
insert into "investmentApp_asset"(id,description,code) values(149,'Coelba','CEEB3');
insert into "investmentApp_asset"(id,description,code) values(150,'Coelba','CEEB5');
insert into "investmentApp_asset"(id,description,code) values(151,'Coelce','COCE3');
insert into "investmentApp_asset"(id,description,code) values(152,'Coelce','COCE5');
insert into "investmentApp_asset"(id,description,code) values(153,'Cogna Educação S.A.','COGN3');
insert into "investmentApp_asset"(id,description,code) values(154,'Comgas','CGAS3');
insert into "investmentApp_asset"(id,description,code) values(155,'Comgas','CGAS5');
insert into "investmentApp_asset"(id,description,code) values(156,'Companhia de Locação das Américas','LCAM3');
insert into "investmentApp_asset"(id,description,code) values(157,'Companhia de Saneamento Básico do Estado de São Paulo - SABESP','SBSP3');
insert into "investmentApp_asset"(id,description,code) values(158,'Companhia Energética de Minas Gerais','CMIG3');
insert into "investmentApp_asset"(id,description,code) values(159,'Companhia Energética de Minas Gerais','CMIG4');
insert into "investmentApp_asset"(id,description,code) values(160,'Companhia Paranaense de Energia - COPEL','CPLE6');
insert into "investmentApp_asset"(id,description,code) values(161,'Companhia Paranaense de Energia - COPEL','CPLE3');
insert into "investmentApp_asset"(id,description,code) values(162,'Companhia Siderúrgica Nacional','CSNA3');
insert into "investmentApp_asset"(id,description,code) values(163,'Const A Lind','CALI3');
insert into "investmentApp_asset"(id,description,code) values(164,'Const A Lind','CALI4');
insert into "investmentApp_asset"(id,description,code) values(165,'CopaSA','CSMG3');
insert into "investmentApp_asset"(id,description,code) values(166,'Copel','CPLE5');
insert into "investmentApp_asset"(id,description,code) values(167,'Cor Ribeiro','CORR4');
insert into "investmentApp_asset"(id,description,code) values(168,'CoSAn Log','RLOG3');
insert into "investmentApp_asset"(id,description,code) values(169,'Cosan S.A.','CSAN3');
insert into "investmentApp_asset"(id,description,code) values(170,'Cosern','CSRN3');
insert into "investmentApp_asset"(id,description,code) values(171,'Cosern','CSRN5');
insert into "investmentApp_asset"(id,description,code) values(172,'Cosern','CSRN6');
insert into "investmentApp_asset"(id,description,code) values(173,'Coteminas','CTNM3');
insert into "investmentApp_asset"(id,description,code) values(174,'Coteminas','CTNM4');
insert into "investmentApp_asset"(id,description,code) values(175,'CPFL Energia S.A.','CPFE3');
insert into "investmentApp_asset"(id,description,code) values(176,'Cr2','CRDE3');
insert into "investmentApp_asset"(id,description,code) values(177,'Cristal','CRPG3');
insert into "investmentApp_asset"(id,description,code) values(178,'Cristal','CRPG5');
insert into "investmentApp_asset"(id,description,code) values(179,'Cristal','CRPG6');
insert into "investmentApp_asset"(id,description,code) values(180,'Cruzeiro Edu','CSED3');
insert into "investmentApp_asset"(id,description,code) values(181,'CSHG Logistica - Fundo De Investimento Imobiliario','HGLG11');
insert into "investmentApp_asset"(id,description,code) values(182,'Csnmineracao','CMIN3');
insert into "investmentApp_asset"(id,description,code) values(183,'Csu Cardsyst','CARD3');
insert into "investmentApp_asset"(id,description,code) values(184,'Cury S/A','CURY3');
insert into "investmentApp_asset"(id,description,code) values(185,'CVC Brasil Operadora e Agência de Viagens S.A.','CVCB3');
insert into "investmentApp_asset"(id,description,code) values(186,'Cyre Com Ccp','CCPR3');
insert into "investmentApp_asset"(id,description,code) values(187,'Cyrela Brazil Realty S.A. Empreendimentos e Participações','CYRE3');
insert into "investmentApp_asset"(id,description,code) values(188,'D1000 Vfarma','DMVF3');
insert into "investmentApp_asset"(id,description,code) values(189,'DaSA','DASA3');
insert into "investmentApp_asset"(id,description,code) values(190,'Desktop','DESK3');
insert into "investmentApp_asset"(id,description,code) values(191,'Dimed','PNVL3');
insert into "investmentApp_asset"(id,description,code) values(192,'Dimed','PNVL4');
insert into "investmentApp_asset"(id,description,code) values(193,'Direcional','DIRR3');
insert into "investmentApp_asset"(id,description,code) values(194,'Dohler','DOHL3');
insert into "investmentApp_asset"(id,description,code) values(195,'Dohler','DOHL4');
insert into "investmentApp_asset"(id,description,code) values(196,'Dommo','DMMO3');
insert into "investmentApp_asset"(id,description,code) values(197,'Dotz S.A.','DOTZ3');
insert into "investmentApp_asset"(id,description,code) values(198,'Dtcom Direct','DTCY3');
insert into "investmentApp_asset"(id,description,code) values(199,'Duratex','DTEX3');
insert into "investmentApp_asset"(id,description,code) values(200,'EcoRodovias Infraestrutura e Logística S.A.','ECOR3');
insert into "investmentApp_asset"(id,description,code) values(201,'EDP - Energias do Brasil S.A.','ENBR3');
insert into "investmentApp_asset"(id,description,code) values(202,'Elektro','EKTR3');
insert into "investmentApp_asset"(id,description,code) values(203,'Elektro','EKTR4');
insert into "investmentApp_asset"(id,description,code) values(204,'Eletrobras','ELET5');
insert into "investmentApp_asset"(id,description,code) values(205,'Eletromidia','ELMD3');
insert into "investmentApp_asset"(id,description,code) values(206,'Eletropar','LIPR3');
insert into "investmentApp_asset"(id,description,code) values(207,'Emae','EMAE3');
insert into "investmentApp_asset"(id,description,code) values(208,'Emae','EMAE4');
insert into "investmentApp_asset"(id,description,code) values(209,'Embraer S.A.','EMBR3');
insert into "investmentApp_asset"(id,description,code) values(210,'Enauta Part','ENAT3');
insert into "investmentApp_asset"(id,description,code) values(211,'Encorpar','ECPR3');
insert into "investmentApp_asset"(id,description,code) values(212,'Encorpar','ECPR4');
insert into "investmentApp_asset"(id,description,code) values(213,'EnergiSA','ENGI');
insert into "investmentApp_asset"(id,description,code) values(214,'EnergiSA','ENGI11');
insert into "investmentApp_asset"(id,description,code) values(215,'EnergiSA','ENGI3');
insert into "investmentApp_asset"(id,description,code) values(216,'EnergiSA','ENGI4');
insert into "investmentApp_asset"(id,description,code) values(217,'EnergiSA Mt','ENMT3');
insert into "investmentApp_asset"(id,description,code) values(218,'EnergiSA Mt','ENMT4');
insert into "investmentApp_asset"(id,description,code) values(219,'Eneva','ENEV3');
insert into "investmentApp_asset"(id,description,code) values(220,'Engie Brasil Energia S.A.','EGIE3');
insert into "investmentApp_asset"(id,description,code) values(221,'Enjoei','ENJU3');
insert into "investmentApp_asset"(id,description,code) values(222,'Eqtl Para','EQPA3');
insert into "investmentApp_asset"(id,description,code) values(223,'Eqtl Para','EQPA5');
insert into "investmentApp_asset"(id,description,code) values(224,'Eqtl Para','EQPA6');
insert into "investmentApp_asset"(id,description,code) values(225,'Eqtl Para','EQPA7');
insert into "investmentApp_asset"(id,description,code) values(226,'Equatorial Energia S.A.','EQTL3');
insert into "investmentApp_asset"(id,description,code) values(227,'Espacolaser','ESPA3');
insert into "investmentApp_asset"(id,description,code) values(228,'Estácio Participações S.A.','YDUQ3');
insert into "investmentApp_asset"(id,description,code) values(229,'Estapar','ALPK3');
insert into "investmentApp_asset"(id,description,code) values(230,'Estrela','ESTR3');
insert into "investmentApp_asset"(id,description,code) values(231,'Estrela','ESTR4');
insert into "investmentApp_asset"(id,description,code) values(232,'Eternit','ETER3');
insert into "investmentApp_asset"(id,description,code) values(233,'Eucatex','EUCA3');
insert into "investmentApp_asset"(id,description,code) values(234,'Eucatex','EUCA4');
insert into "investmentApp_asset"(id,description,code) values(235,'Even','EVEN3');
insert into "investmentApp_asset"(id,description,code) values(236,'Excelsior','BAUH4');
insert into "investmentApp_asset"(id,description,code) values(237,'Eztec','EZTC3');
insert into "investmentApp_asset"(id,description,code) values(238,'Fator Verita','VRTA11');
insert into "investmentApp_asset"(id,description,code) values(239,'FD Invest Imob Hotel Maxinvest','HTMX11');
insert into "investmentApp_asset"(id,description,code) values(240,'Fer Heringer','FHER3');
insert into "investmentApp_asset"(id,description,code) values(241,'FerbaSA','FESA3');
insert into "investmentApp_asset"(id,description,code) values(242,'FerbaSA','FESA4');
insert into "investmentApp_asset"(id,description,code) values(243,'Fleury S.A.','FLRY3');
insert into "investmentApp_asset"(id,description,code) values(244,'Focus On','POWE3');
insert into "investmentApp_asset"(id,description,code) values(245,'Fras Le','FRAS3');
insert into "investmentApp_asset"(id,description,code) values(246,'Fundo de Investimento Imobiliario - FII Brasil Plural Absoluto Fundo de Fundos','BPFF11');
insert into "investmentApp_asset"(id,description,code) values(247,'Fundo Investimento Imobiliario Rbr Properties Fii','RBRP11');
insert into "investmentApp_asset"(id,description,code) values(248,'GafiSA','GFSA3');
insert into "investmentApp_asset"(id,description,code) values(249,'Generalshopp','GSHP3');
insert into "investmentApp_asset"(id,description,code) values(250,'Ger Paranap','GEPA3');
insert into "investmentApp_asset"(id,description,code) values(251,'Ger Paranap','GEPA4');
insert into "investmentApp_asset"(id,description,code) values(252,'Gerdau Met','GOAU3');
insert into "investmentApp_asset"(id,description,code) values(253,'Gerdau S.A.','GGBR3');
insert into "investmentApp_asset"(id,description,code) values(254,'Gerdau S.A.','GGBR4');
insert into "investmentApp_asset"(id,description,code) values(255,'Getninjas','NINJ3');
insert into "investmentApp_asset"(id,description,code) values(256,'Gol Linhas Aéreas Inteligentes S.A.','GOLL4');
insert into "investmentApp_asset"(id,description,code) values(257,'Gp Invest','GPIV33');
insert into "investmentApp_asset"(id,description,code) values(258,'GPA Companhia Brasileira de Distribuição','PCAR3');
insert into "investmentApp_asset"(id,description,code) values(259,'Gpc Part','GPCP3');
insert into "investmentApp_asset"(id,description,code) values(260,'GPS','GGPS3');
insert into "investmentApp_asset"(id,description,code) values(261,'Grazziotin','CGRA3');
insert into "investmentApp_asset"(id,description,code) values(262,'Grazziotin','CGRA4');
insert into "investmentApp_asset"(id,description,code) values(263,'Grendene S.A.','GRND3');
insert into "investmentApp_asset"(id,description,code) values(264,'Grupo Mateus S.A.','GMAT3');
insert into "investmentApp_asset"(id,description,code) values(265,'Grupo Sbf','SBFG3');
insert into "investmentApp_asset"(id,description,code) values(266,'Grupo Soma','SOMA3');
insert into "investmentApp_asset"(id,description,code) values(267,'Guararapes','GUAR3');
insert into "investmentApp_asset"(id,description,code) values(268,'Habitasul','HBTS5');
insert into "investmentApp_asset"(id,description,code) values(269,'Haga S/A','HAGA3');
insert into "investmentApp_asset"(id,description,code) values(270,'Haga S/A','HAGA4');
insert into "investmentApp_asset"(id,description,code) values(271,'Hapvida','HAPV3');
insert into "investmentApp_asset"(id,description,code) values(272,'Hbr Realty','HBRE3');
insert into "investmentApp_asset"(id,description,code) values(273,'Hectare CE Fundo de Investimento Imobiliário','HCTR11');
insert into "investmentApp_asset"(id,description,code) values(274,'HEDGE Brasil Shopping Fundo de Investimento Imobiliario','HGBS11');
insert into "investmentApp_asset"(id,description,code) values(275,'Hedge Top FOFII 3','HFOF11');
insert into "investmentApp_asset"(id,description,code) values(276,'Helbor Empreendimentos S.A.','HBOR3');
insert into "investmentApp_asset"(id,description,code) values(277,'Hercules','HETA3');
insert into "investmentApp_asset"(id,description,code) values(278,'Hercules','HETA4');
insert into "investmentApp_asset"(id,description,code) values(279,'Hidrovias','HBSA3');
insert into "investmentApp_asset"(id,description,code) values(280,'Hoteis Othon','HOOT4');
insert into "investmentApp_asset"(id,description,code) values(281,'Hypera S.A.','HYPE3');
insert into "investmentApp_asset"(id,description,code) values(282,'Igb S/A','IGBR3');
insert into "investmentApp_asset"(id,description,code) values(283,'Iguatemi Empresa de Shopping Centers S.A.','IGTA3');
insert into "investmentApp_asset"(id,description,code) values(284,'Ihpardini','PARD3');
insert into "investmentApp_asset"(id,description,code) values(285,'Inds Romi','ROMI3');
insert into "investmentApp_asset"(id,description,code) values(286,'Indusval','IDVL3');
insert into "investmentApp_asset"(id,description,code) values(287,'Indusval','IDVL4');
insert into "investmentApp_asset"(id,description,code) values(288,'Inepar','INEP3');
insert into "investmentApp_asset"(id,description,code) values(289,'Inepar','INEP4');
insert into "investmentApp_asset"(id,description,code) values(290,'Infracomm','IFCM3');
insert into "investmentApp_asset"(id,description,code) values(291,'Intelbras','INTB3');
insert into "investmentApp_asset"(id,description,code) values(292,'Intermedica','GNDI3');
insert into "investmentApp_asset"(id,description,code) values(293,'International Meal Company Alimentacao S.A.','MEAL3');
insert into "investmentApp_asset"(id,description,code) values(294,'Iochpe-Maxion S.A.','MYPK3');
insert into "investmentApp_asset"(id,description,code) values(295,'Irani','RANI3');
insert into "investmentApp_asset"(id,description,code) values(296,'Irani','RANI4');
insert into "investmentApp_asset"(id,description,code) values(297,'IRB-Brasil Resseguros S.A.','IRBR3');
insert into "investmentApp_asset"(id,description,code) values(298,'iShares Ibovespa Fundo de Índice ETF','BOVA11');
insert into "investmentApp_asset"(id,description,code) values(299,'iShares S&P 500 Fundo de Investimento - Investimento No Exterior','IVVB11');
insert into "investmentApp_asset"(id,description,code) values(300,'Itaú Unibanco Holding S.A.','ITUB4');
insert into "investmentApp_asset"(id,description,code) values(301,'Itaú Unibanco Holding S.A.','ITUB3');
insert into "investmentApp_asset"(id,description,code) values(302,'Itaúsa - Investimentos Itaú S.A.','ITSA4');
insert into "investmentApp_asset"(id,description,code) values(303,'Itausa - Investimentos Itau S.A.','ITSA3');
insert into "investmentApp_asset"(id,description,code) values(304,'J B Duarte','JBDU3');
insert into "investmentApp_asset"(id,description,code) values(305,'J B Duarte','JBDU4');
insert into "investmentApp_asset"(id,description,code) values(306,'Jallesmachad','JALL3');
insert into "investmentApp_asset"(id,description,code) values(307,'JBS S.A.','JBSS3');
insert into "investmentApp_asset"(id,description,code) values(308,'JD COM DRN','JDCO34');
insert into "investmentApp_asset"(id,description,code) values(309,'JereisSAti','JPSA3');
insert into "investmentApp_asset"(id,description,code) values(310,'JHSF Participacoes S.A.','JHSF3');
insert into "investmentApp_asset"(id,description,code) values(311,'Joao Fortes','JFEN3');
insert into "investmentApp_asset"(id,description,code) values(312,'JoSApar','JOPA3');
insert into "investmentApp_asset"(id,description,code) values(313,'JoSApar','JOPA4');
insert into "investmentApp_asset"(id,description,code) values(314,'Kallas','KLAS3');
insert into "investmentApp_asset"(id,description,code) values(315,'Karsten','CTKA3');
insert into "investmentApp_asset"(id,description,code) values(316,'Karsten','CTKA4');
insert into "investmentApp_asset"(id,description,code) values(317,'Kepler Weber','KEPL3');
insert into "investmentApp_asset"(id,description,code) values(318,'KINEA Renda Imobiliária - Fundo de Investimento Imobiliário','KNRI11');
insert into "investmentApp_asset"(id,description,code) values(319,'Klabin S/A','KLBN3');
insert into "investmentApp_asset"(id,description,code) values(320,'Klabin S/A','KLBN4');
insert into "investmentApp_asset"(id,description,code) values(321,'KLABIN S/A UNT N2','KLBN11');
insert into "investmentApp_asset"(id,description,code) values(322,'Lavvi','LAVV3');
insert into "investmentApp_asset"(id,description,code) values(323,'Le Biscuit','LLBI3');
insert into "investmentApp_asset"(id,description,code) values(324,'Le Biscuit','LLBI4');
insert into "investmentApp_asset"(id,description,code) values(325,'Le Lis Blanc','LLIS3');
insert into "investmentApp_asset"(id,description,code) values(326,'Light S/A','LIGT3');
insert into "investmentApp_asset"(id,description,code) values(327,'Linx','LINX3');
insert into "investmentApp_asset"(id,description,code) values(328,'Localiza Rent a Car S.A.','RENT3');
insert into "investmentApp_asset"(id,description,code) values(329,'Locaweb','LWSA3');
insert into "investmentApp_asset"(id,description,code) values(330,'Log Com Prop','LOGG3');
insert into "investmentApp_asset"(id,description,code) values(331,'Log In','LOGN3');
insert into "investmentApp_asset"(id,description,code) values(332,'Lojas Americ','LAME3');
insert into "investmentApp_asset"(id,description,code) values(333,'Lojas Americanas S.A.','LAME4');
insert into "investmentApp_asset"(id,description,code) values(334,'Lojas MariSA','AMAR3');
insert into "investmentApp_asset"(id,description,code) values(335,'Lojas Renner S.A.','LREN3');
insert into "investmentApp_asset"(id,description,code) values(336,'Lopes Brasil','LPSB3');
insert into "investmentApp_asset"(id,description,code) values(337,'Lupatech','LUPA3');
insert into "investmentApp_asset"(id,description,code) values(338,'M. Dias Branco S.A. Indústria e Comércio de Alimentos','MDIA3');
insert into "investmentApp_asset"(id,description,code) values(339,'Magazine Luiza S.A.','MGLU3');
insert into "investmentApp_asset"(id,description,code) values(340,'Mangels Indl','MGEL4');
insert into "investmentApp_asset"(id,description,code) values(341,'Marcopolo','POMO3');
insert into "investmentApp_asset"(id,description,code) values(342,'Marcopolo','POMO4');
insert into "investmentApp_asset"(id,description,code) values(343,'Marfrig Global Foods S.A.','MRFG3');
insert into "investmentApp_asset"(id,description,code) values(344,'Mater Dei','MATD3');
insert into "investmentApp_asset"(id,description,code) values(345,'Maxi Renda Fundo De Investimento Imobiliaro - FII','MXRF11');
insert into "investmentApp_asset"(id,description,code) values(346,'Melhor Sp','MSPA3');
insert into "investmentApp_asset"(id,description,code) values(347,'Melhor Sp','MSPA4');
insert into "investmentApp_asset"(id,description,code) values(348,'Meliuz','CASH3');
insert into "investmentApp_asset"(id,description,code) values(349,'Melnick','MELK3');
insert into "investmentApp_asset"(id,description,code) values(350,'Merc Brasil','BMEB3');
insert into "investmentApp_asset"(id,description,code) values(351,'Merc Brasil','BMEB4');
insert into "investmentApp_asset"(id,description,code) values(352,'Merc Financ','MERC3');
insert into "investmentApp_asset"(id,description,code) values(353,'Merc Financ','MERC4');
insert into "investmentApp_asset"(id,description,code) values(354,'Merc Invest','BMIN3');
insert into "investmentApp_asset"(id,description,code) values(355,'Merc Invest','BMIN4');
insert into "investmentApp_asset"(id,description,code) values(356,'Merito Desenvolvimento Imobiliario I FII - Fundo de Investimento Imobiliario','MFII11');
insert into "investmentApp_asset"(id,description,code) values(357,'Metal Iguacu','MTIG4');
insert into "investmentApp_asset"(id,description,code) values(358,'Metal Leve','LEVE3');
insert into "investmentApp_asset"(id,description,code) values(359,'Metalfrio','FRIO3');
insert into "investmentApp_asset"(id,description,code) values(360,'Metalurgica Gerdau S.A.','GOAU4');
insert into "investmentApp_asset"(id,description,code) values(361,'MetiSA','MTSA3');
insert into "investmentApp_asset"(id,description,code) values(362,'MetiSA','MTSA4');
insert into "investmentApp_asset"(id,description,code) values(363,'Mills Estruturas e Servicos de Engenharia S.A.','MILS3');
insert into "investmentApp_asset"(id,description,code) values(364,'Minerva','BEEF');
insert into "investmentApp_asset"(id,description,code) values(365,'Minerva','BEEF3');
insert into "investmentApp_asset"(id,description,code) values(366,'Minupar','MNPR3');
insert into "investmentApp_asset"(id,description,code) values(367,'Mitre Realty','MTRE3');
insert into "investmentApp_asset"(id,description,code) values(368,'Mmx Miner','MMXM11');
insert into "investmentApp_asset"(id,description,code) values(369,'Mmx Miner','MMXM3');
insert into "investmentApp_asset"(id,description,code) values(370,'Mobly','MBLY3');
insert into "investmentApp_asset"(id,description,code) values(371,'Mont Aranha','MOAR3');
insert into "investmentApp_asset"(id,description,code) values(372,'Mosaico','MOSI3');
insert into "investmentApp_asset"(id,description,code) values(373,'Moura Dubeux','MDNE3');
insert into "investmentApp_asset"(id,description,code) values(374,'Movida Participacoes S.A.','MOVI3');
insert into "investmentApp_asset"(id,description,code) values(375,'MRV Engenharia e Participações S.A.','MRVE3');
insert into "investmentApp_asset"(id,description,code) values(376,'Multilaser','MLAS3');
insert into "investmentApp_asset"(id,description,code) values(377,'Multiplan Empreendimentos Imobiliários S.A.','MULT3');
insert into "investmentApp_asset"(id,description,code) values(378,'Mundial','MNDL3');
insert into "investmentApp_asset"(id,description,code) values(379,'Natura &Co Holding S.A.','NTCO3');
insert into "investmentApp_asset"(id,description,code) values(380,'Natura Cosméticos S.A.','NATU3');
insert into "investmentApp_asset"(id,description,code) values(381,'Neoenergia','NEOE3');
insert into "investmentApp_asset"(id,description,code) values(382,'Neogrid','NGRD3');
insert into "investmentApp_asset"(id,description,code) values(383,'Nord Brasil','BNBR3');
insert into "investmentApp_asset"(id,description,code) values(384,'Nordon Met','NORD3');
insert into "investmentApp_asset"(id,description,code) values(385,'Nutriplant','NUTR3');
insert into "investmentApp_asset"(id,description,code) values(386,'Oceanpact','OPCT3');
insert into "investmentApp_asset"(id,description,code) values(387,'Odontoprev','ODPV3');
insert into "investmentApp_asset"(id,description,code) values(388,'Oi','OIBR4');
insert into "investmentApp_asset"(id,description,code) values(389,'Oi S.A.','OIBR3');
insert into "investmentApp_asset"(id,description,code) values(390,'Omega Ger','OMGE3');
insert into "investmentApp_asset"(id,description,code) values(391,'Orizon','ORVR3');
insert into "investmentApp_asset"(id,description,code) values(392,'Osx Brasil','OSXB3');
insert into "investmentApp_asset"(id,description,code) values(393,'Ourofino S/A','OFSA3');
insert into "investmentApp_asset"(id,description,code) values(394,'Padtec','PDTC3');
insert into "investmentApp_asset"(id,description,code) values(395,'Pague Menos','PGMN3');
insert into "investmentApp_asset"(id,description,code) values(396,'Panatlantica','PATI3');
insert into "investmentApp_asset"(id,description,code) values(397,'Panatlantica','PATI4');
insert into "investmentApp_asset"(id,description,code) values(398,'Par Al Bahia','PEAB3');
insert into "investmentApp_asset"(id,description,code) values(399,'Par Al Bahia','PEAB4');
insert into "investmentApp_asset"(id,description,code) values(400,'Paranapanema','PMAM3');
insert into "investmentApp_asset"(id,description,code) values(401,'Pdg Realt','PDGR3');
insert into "investmentApp_asset"(id,description,code) values(402,'Pet Center Comércio e Participações S.A.','PETZ3');
insert into "investmentApp_asset"(id,description,code) values(403,'Pet Manguinh','RPMG3');
insert into "investmentApp_asset"(id,description,code) values(404,'Petróleo Brasileiro S.A. - Petrobras','PETR4');
insert into "investmentApp_asset"(id,description,code) values(405,'Petróleo Brasileiro S.A. - Petrobras','PETR3');
insert into "investmentApp_asset"(id,description,code) values(406,'Petrorecôncavo S.A.','RECV3');
insert into "investmentApp_asset"(id,description,code) values(407,'Petrorio','PRIO3');
insert into "investmentApp_asset"(id,description,code) values(408,'Pettenati','PTNT3');
insert into "investmentApp_asset"(id,description,code) values(409,'Pettenati','PTNT4');
insert into "investmentApp_asset"(id,description,code) values(410,'Pine','PINE4');
insert into "investmentApp_asset"(id,description,code) values(411,'Planoeplano','PLPL3');
insert into "investmentApp_asset"(id,description,code) values(412,'Plascar Part','PLAS3');
insert into "investmentApp_asset"(id,description,code) values(413,'Pomifrutas','FRTA3');
insert into "investmentApp_asset"(id,description,code) values(414,'Porto Seguro S.A.','PSSA3');
insert into "investmentApp_asset"(id,description,code) values(415,'Porto Vm','PSVM11');
insert into "investmentApp_asset"(id,description,code) values(416,'Portobello','PTBL3');
insert into "investmentApp_asset"(id,description,code) values(417,'Positivo Tec','POSI3');
insert into "investmentApp_asset"(id,description,code) values(418,'Ppla','PPLA11');
insert into "investmentApp_asset"(id,description,code) values(419,'Priner','PRNR3');
insert into "investmentApp_asset"(id,description,code) values(420,'Profarma','PFRM3');
insert into "investmentApp_asset"(id,description,code) values(421,'Qualicorp Consultoria e Corretora de Seguros S.A.','QUAL3');
insert into "investmentApp_asset"(id,description,code) values(422,'Quero Quero','LJQQ3');
insert into "investmentApp_asset"(id,description,code) values(423,'Raia Drogasil S.A.','RADL3');
insert into "investmentApp_asset"(id,description,code) values(424,'Raizen','RAIZ4');
insert into "investmentApp_asset"(id,description,code) values(425,'Randon Part','RAPT3');
insert into "investmentApp_asset"(id,description,code) values(426,'Randon Part','RAPT4');
insert into "investmentApp_asset"(id,description,code) values(427,'RBR Rendimento High Grade','RBRR11');
insert into "investmentApp_asset"(id,description,code) values(428,'Recrusul','RCSL3');
insert into "investmentApp_asset"(id,description,code) values(429,'Recrusul','RCSL4');
insert into "investmentApp_asset"(id,description,code) values(430,'Rede D Or','RDOR3');
insert into "investmentApp_asset"(id,description,code) values(431,'Rede Energia','REDE3');
insert into "investmentApp_asset"(id,description,code) values(432,'Renova','RNEW11');
insert into "investmentApp_asset"(id,description,code) values(433,'Renova','RNEW3');
insert into "investmentApp_asset"(id,description,code) values(434,'Renova','RNEW4');
insert into "investmentApp_asset"(id,description,code) values(435,'Riosulense','RSUL4');
insert into "investmentApp_asset"(id,description,code) values(436,'Rni','RDNI3');
insert into "investmentApp_asset"(id,description,code) values(437,'Rodobens','RBNS11');
insert into "investmentApp_asset"(id,description,code) values(438,'Rossi Resid','RSID3');
insert into "investmentApp_asset"(id,description,code) values(439,'Rumo S.A.','RAIL3');
insert into "investmentApp_asset"(id,description,code) values(440,'Sanepar','SAPR11');
insert into "investmentApp_asset"(id,description,code) values(441,'Sanepar','SAPR3');
insert into "investmentApp_asset"(id,description,code) values(442,'Sanepar','SAPR4');
insert into "investmentApp_asset"(id,description,code) values(443,'Sansuy','SNSY3');
insert into "investmentApp_asset"(id,description,code) values(444,'Sansuy','SNSY5');
insert into "investmentApp_asset"(id,description,code) values(445,'Sansuy','SNSY6');
insert into "investmentApp_asset"(id,description,code) values(446,'Santander Br','SANB4');
insert into "investmentApp_asset"(id,description,code) values(447,'Santanense','CTSA3');
insert into "investmentApp_asset"(id,description,code) values(448,'Santanense','CTSA4');
insert into "investmentApp_asset"(id,description,code) values(449,'Santos Brp','STBP3');
insert into "investmentApp_asset"(id,description,code) values(450,'Sao Carlos','SCAR3');
insert into "investmentApp_asset"(id,description,code) values(451,'Sao Martinho','SMTO3');
insert into "investmentApp_asset"(id,description,code) values(452,'Saraiva Livr','SLED3');
insert into "investmentApp_asset"(id,description,code) values(453,'Saraiva Livr','SLED4');
insert into "investmentApp_asset"(id,description,code) values(454,'Schulz','SHUL4');
insert into "investmentApp_asset"(id,description,code) values(455,'Seg Al Bahia','CSAB3');
insert into "investmentApp_asset"(id,description,code) values(456,'Seg Al Bahia','CSAB4');
insert into "investmentApp_asset"(id,description,code) values(457,'Sequoia Log','SEQL3');
insert into "investmentApp_asset"(id,description,code) values(458,'Ser Educa','SEER3');
insert into "investmentApp_asset"(id,description,code) values(459,'Simpar','SIMH3');
insert into "investmentApp_asset"(id,description,code) values(460,'Sinqia S.A.','SQIA3');
insert into "investmentApp_asset"(id,description,code) values(461,'Slc Agricola','SLCE3');
insert into "investmentApp_asset"(id,description,code) values(462,'Smart Fit','SMFT3');
insert into "investmentApp_asset"(id,description,code) values(463,'Smiles Fidelidade S.A.','SMLS3');
insert into "investmentApp_asset"(id,description,code) values(464,'Sondotecnica','SOND3');
insert into "investmentApp_asset"(id,description,code) values(465,'Sondotecnica','SOND5');
insert into "investmentApp_asset"(id,description,code) values(466,'Sondotecnica','SOND6');
insert into "investmentApp_asset"(id,description,code) values(467,'Springs','SGPS3');
insert into "investmentApp_asset"(id,description,code) values(468,'Spturis','AHEB3');
insert into "investmentApp_asset"(id,description,code) values(469,'Spturis','AHEB5');
insert into "investmentApp_asset"(id,description,code) values(470,'Spturis','AHEB6');
insert into "investmentApp_asset"(id,description,code) values(471,'Sul America','SULA11');
insert into "investmentApp_asset"(id,description,code) values(472,'Sul America','SULA3');
insert into "investmentApp_asset"(id,description,code) values(473,'Sul America','SULA4');
insert into "investmentApp_asset"(id,description,code) values(474,'Suzano S.A.','SUZB3');
insert into "investmentApp_asset"(id,description,code) values(475,'TaeSA','TAEE3');
insert into "investmentApp_asset"(id,description,code) values(476,'TaeSA','TAEE4');
insert into "investmentApp_asset"(id,description,code) values(477,'Taurus Armas','TASA3');
insert into "investmentApp_asset"(id,description,code) values(478,'Taurus Armas S.A.','TASA4');
insert into "investmentApp_asset"(id,description,code) values(479,'Tc','TRAD3');
insert into "investmentApp_asset"(id,description,code) values(480,'Technos','TECN3');
insert into "investmentApp_asset"(id,description,code) values(481,'Tecnisa S.A.','TCSA3');
insert into "investmentApp_asset"(id,description,code) values(482,'Tecnosolo','TCNO3');
insert into "investmentApp_asset"(id,description,code) values(483,'Tecnosolo','TCNO4');
insert into "investmentApp_asset"(id,description,code) values(484,'Tegma','TGMA3');
insert into "investmentApp_asset"(id,description,code) values(485,'Tegra Incorporadora','TEGA3');
insert into "investmentApp_asset"(id,description,code) values(486,'Teka','TEKA3');
insert into "investmentApp_asset"(id,description,code) values(487,'Teka','TEKA4');
insert into "investmentApp_asset"(id,description,code) values(488,'Tekno','TKNO4');
insert into "investmentApp_asset"(id,description,code) values(489,'Telebras','TELB3');
insert into "investmentApp_asset"(id,description,code) values(490,'Telebras','TELB4');
insert into "investmentApp_asset"(id,description,code) values(491,'Telef Brasil','VIVT3');
insert into "investmentApp_asset"(id,description,code) values(492,'Telefônica Brasil S.A.','VIVT4');
insert into "investmentApp_asset"(id,description,code) values(493,'Tenda','TEND3');
insert into "investmentApp_asset"(id,description,code) values(494,'Terniumsa DRN','TXSA34');
insert into "investmentApp_asset"(id,description,code) values(495,'Terra Santa','TESA3');
insert into "investmentApp_asset"(id,description,code) values(496,'TerraSAntapa','LAND3');
insert into "investmentApp_asset"(id,description,code) values(497,'Tex Renaux','TXRX3');
insert into "investmentApp_asset"(id,description,code) values(498,'TIM S.A.','TIMS3');
insert into "investmentApp_asset"(id,description,code) values(499,'Time For Fun','SHOW3');
insert into "investmentApp_asset"(id,description,code) values(500,'TOTVS S.A.','TOTS3');
insert into "investmentApp_asset"(id,description,code) values(501,'Track Field','TFCO4');
insert into "investmentApp_asset"(id,description,code) values(502,'Tran Paulist','TRPL3');
insert into "investmentApp_asset"(id,description,code) values(503,'Tran Paulist','TRPL4');
insert into "investmentApp_asset"(id,description,code) values(504,'Transmissora Aliança de Energia Elétrica S.A.','TAEE11');
insert into "investmentApp_asset"(id,description,code) values(505,'TreviSA','LUXM4');
insert into "investmentApp_asset"(id,description,code) values(506,'Trisul','TRIS3');
insert into "investmentApp_asset"(id,description,code) values(507,'Triunfo Part','TPIS3');
insert into "investmentApp_asset"(id,description,code) values(508,'TRX Real State','TRXF11');
insert into "investmentApp_asset"(id,description,code) values(509,'Tupy','TUPY3');
insert into "investmentApp_asset"(id,description,code) values(510,'UBS BR Office','RECT11');
insert into "investmentApp_asset"(id,description,code) values(511,'Ultrapar Participações S.A.','UGPA3');
insert into "investmentApp_asset"(id,description,code) values(512,'UnicaSA','UCAS3');
insert into "investmentApp_asset"(id,description,code) values(513,'Unipar','UNIP3');
insert into "investmentApp_asset"(id,description,code) values(514,'Unipar','UNIP5');
insert into "investmentApp_asset"(id,description,code) values(515,'Unipar','UNIP6');
insert into "investmentApp_asset"(id,description,code) values(516,'Usiminas','USIM3');
insert into "investmentApp_asset"(id,description,code) values(517,'Usiminas','USIM6');
insert into "investmentApp_asset"(id,description,code) values(518,'Usinas Siderúrgicas de Minas Gerais S.A.','USIM5');
insert into "investmentApp_asset"(id,description,code) values(519,'Vale S.A.','VALE3');
insert into "investmentApp_asset"(id,description,code) values(520,'Valid Solucoes S.A.','VLID3');
insert into "investmentApp_asset"(id,description,code) values(521,'Vamos','VAMO3');
insert into "investmentApp_asset"(id,description,code) values(522,'VBI Losístico','LVBI11');
insert into "investmentApp_asset"(id,description,code) values(523,'VBI Prime Properties','PVBI11');
insert into "investmentApp_asset"(id,description,code) values(524,'Via Varejo S.A.','VIIA3');
insert into "investmentApp_asset"(id,description,code) values(525,'Vibra Energia S.A.','VBBR3');
insert into "investmentApp_asset"(id,description,code) values(526,'Vinci Logistica Fundo Investimento Imobiliario FII','VILG11');
insert into "investmentApp_asset"(id,description,code) values(527,'Vittia Fertilizantes S.A.','VITT3');
insert into "investmentApp_asset"(id,description,code) values(528,'Vivara Participacoes S.A.','VIVA3');
insert into "investmentApp_asset"(id,description,code) values(529,'Viveo','VVEO3');
insert into "investmentApp_asset"(id,description,code) values(530,'Viver','VIVR3');
insert into "investmentApp_asset"(id,description,code) values(531,'Vulcabras','VULC3');
insert into "investmentApp_asset"(id,description,code) values(532,'Wdc Networks','LVTC3');
insert into "investmentApp_asset"(id,description,code) values(533,'WEG S.A.','WEGE3');
insert into "investmentApp_asset"(id,description,code) values(534,'Westwing','WEST3');
insert into "investmentApp_asset"(id,description,code) values(535,'Wetzel S/A','MWET3');
insert into "investmentApp_asset"(id,description,code) values(536,'Wetzel S/A','MWET4');
insert into "investmentApp_asset"(id,description,code) values(537,'Whirlpool','WHRL3');
insert into "investmentApp_asset"(id,description,code) values(538,'Whirlpool','WHRL4');
insert into "investmentApp_asset"(id,description,code) values(539,'Wilson Sons','WSON33');
insert into "investmentApp_asset"(id,description,code) values(540,'Wiz Solucoes e Corretagem de Seguros S.A.','WIZS3');
insert into "investmentApp_asset"(id,description,code) values(541,'Wlm Ind Com','WLMM3');
insert into "investmentApp_asset"(id,description,code) values(542,'Wlm Ind Com','WLMM4');