# Generated by Django 4.0.6 on 2022-07-13 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('change_percent', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('assetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentApp.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TimeField()),
                ('date_updated', models.DateTimeField()),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('assetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentApp.asset')),
                ('cotationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentApp.cotation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
