# Generated by Django 4.0.6 on 2022-07-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmentApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
